### ISSUE TITLE
DS720+

### ISSUE THREAD

**Issue by skogarfoss** [davidcava/privoxy-dsm#2]
Dear David

I compiled and successfully tested a geminilake-spk on my DS720+ and would be happy to publish it on your repository

kind regards
Ueli

**Comment by davidcava** [comment]
Hello
Thanks for the message and sorry for the 2 months response delay.
I have now uploaded the packages for the last version of Privoxy and including all current architectures.
To avoid any tempering risk I do not upload binaries that I have not generated myself. But if you have had to make any adjustment in the source/config files, I welcome any suggestion.
best regards
David
