### ISSUE TITLE
flaresolverr keeps restarting after using Privoxy and cannot be used

### ISSUE THREAD

**Issue by yjiawqgj** [davidcava/privoxy-dsm#4]
According to your settings, 127.0.0.1 has been changed to 0
0.0.0 to receive docker’s flaresolverr container request, flaresolverr has configured the variable HTTP_PROXY=http://dsm host:9050, but after the configuration is complete, flaresolverrg keeps restarting and cannot be used normally.

**Comment by davidcava** [comment]
well no idea what flaresolver is about, and 1 year long issue so closing
